version: '3'
services:
  node:
    image: '96tm/rs-school-web'
    container_name: 'node-container'
    build:
      context: .
      dockerfile: node.Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - .:/usr/app/
    ports:
      - ${HOST_PORT}:${PORT}
    networks:
      - nodejs_network
  db:
    image: '96tm/rs-school-db'
    container_name: 'db-container'
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - ${POSTGRES_PORT_HOST}:${POSTGRES_PORT}
    networks:
      - nodejs_network
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
networks:
  nodejs_network:
    driver: bridge
