version: '3'
services:
  node:
    build:
      dockerfile: ./node.Dockerfile
    ports:
      - ${HOST_PORT}:${PORT}
    depends_on:
      - db
    ENVIRONMENT:
      - PORT=4000
      - HOST_PORT=8080
  db:
    build:
      dockerfile: ./db.Dockerfile
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PORT=5432
