version: '3'
services:
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    restart: always
    volumes:
      - .:/usr/app/
    ports:
      - ${HOST_PORT}:${PORT}
    networks:
      - nodejs_network
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - nodejs_network

networks:
  nodejs_network:
    driver: bridge
